import { IMovieDetail } from 'common';

export const movieDetailMock: IMovieDetail = {
  Actors: 'Ben Affleck, Henry Cavill, Amy Adams',
  Awards: '14 wins & 31 nominations',
  BoxOffice: '$330,360,194',
  Country: 'United States',
  DVD: '19 Jul 2016',
  Director: 'Zack Snyder',
  Genre: 'Action, Adventure, Sci-Fi',
  Language: 'English',
  Metascore: '44',
  Plot: 'The general public is concerned over having Superman on their planet',
  Poster: '/poster.jpg',
  Production: 'N/A',
  Rated: 'PG-13',
  Ratings: [
    { Source: 'Internet Movie Database', Value: '6.4/10' },
    { Source: 'Rotten Tomatoes', Value: '29%' },
  ],
  Released: '25 Mar 2016',
  Response: 'True',
  Runtime: '151 min',
  Title: 'Batman v Superman: Dawn of Justice',
  Type: 'movie',
  Website: 'N/A',
  Writer: 'Chris Terrio, David S. Goyer, Bob Kane',
  Year: '2016',
  imdbID: 'tt2975590',
  imdbRating: '6.4',
  imdbVotes: '708,556',
};
